name: imgcmp
on:
  push:
    branches:
      - main
      - master
jobs:
  imgcmp:
    if: startsWith(github.head_ref, 'actions/imgcmp/') != true
    runs-on: ubuntu-latest
    steps:
      - uses: 9sako6/imgcmp@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
