name: imgcmp
on:
  push:
    branches:
      - main
      - master
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    steps:
      - uses: 9sako6/imgcmp@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
